# the compiler: gcc for C program, define as g++ for C++
  CC = gcc
 
  # compiler flags:
  #  -g     - this flag adds debugging information to the executable file
  #  -Wall  - this flag is used to turn on most compiler warnings
  CFLAGS  = -o
 
  # The build target 
  TARGET = a1
 
  all:
	g++ pthreadstime.cpp -o ./yourcode.out -pthread
